# -*- coding: utf-8 -*-
"""Lab4_MHD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gfDVL8gx5mSZkMvFVbxcvE6WA9tQRWD

## Zadanie 1

W pierwszej kolejności wczytujemy dane z pliku csv i dla pewności sprawdzamy jego strukturę.
"""

import pandas as pd

# Dodajemy parametr encoding='ISO-8859-1' aby program mógł wczytać dane
try:
    df = pd.read_csv("Online_Retail.csv", encoding='ISO-8859-1')
    print("Plik wczytany pomyślnie!")
except FileNotFoundError:
    print("Błąd: Upewnij się, że plik Online_Retail.csv został przesłany do Colaba.")

# Sprawdzenie danych
print(df.info())
df.head()

#  Usuwanie brakujących CustomerID
df = df.dropna(subset=['CustomerID'])

#  Czyszczenie wartości numerycznych
df = df[df['Quantity'] > 0]
df = df[df['UnitPrice'] >= 0]

#  Usuwanie duplikatów i poprawa typów
df = df.drop_duplicates()
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Rozbicie daty
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day

# Dodanie miary wartości
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

# Utworzenie tabeli faktów
fact_sales = df[['InvoiceNo', 'StockCode', 'CustomerID', 'InvoiceDate', 'Quantity', 'TotalPrice']]
fact_sales.to_csv("fact_sales.csv", index=False)
print("Tabela faktów została zapisana jako fact_sales.csv")

"""##Zadanie 2

Najpierw wczytujemy dane z obu plików. Do drugiego nie potrzebujemy enkodowania ponieważ biblioteka pandas odczytuje bez problemu pliki z rozszerzeniem ".xlsx".
"""

import pandas as pd

# Wczytanie pierwszego zbioru (CSV)
df1 = pd.read_csv("Online_Retail.csv", encoding='ISO-8859-1')

# Wczytanie drugiego zbioru (Excel)
df2 = pd.read_excel("online_retail_II.xlsx")

print("Zbiory wczytane pomyślnie.")

"""W tym korku upewniamy sie czy nazwy kolumn mają te same nazwy. Warto zwrócić uwagę na 2 plik, w którym "Customer ID" jest oddzielony spacją."""

df1['InvoiceDate'] = pd.to_datetime(df1['InvoiceDate'], format='mixed')
df2['InvoiceDate'] = pd.to_datetime(df2['InvoiceDate'], format='mixed')

# Ujednolicenie kolumny ID klienta
df2 = df2.rename(columns={'Customer ID': 'CustomerID'})

# Czyszczenie danych
df1 = df1.dropna(subset=['CustomerID'])
df2 = df2.dropna(subset=['CustomerID'])

df1 = df1[df1['Quantity'] > 0]
df2 = df2[df2['Quantity'] > 0]

"""W tym kroku łączymy ze sobą dane z obu plików."""

# Łączenie zbiorów
df_all = pd.concat([df1, df2], ignore_index=True)

# Usunięcie duplikatów po połączeniu
df_all = df_all.drop_duplicates()

"""Zapisujemy dane do jednego pliku."""

# Zapisanie zintegrowanej tabeli faktów
df_all.to_csv("fact_sales_integrated.csv", index=False)

print(f"Integracja zakończona. Połączono {len(df_all)} rekordów.")
print("Wynik zapisano w: fact_sales_integrated.csv")